openapi: 3.0.0
info:
  title: Backend API
  contact: {}
  version: '1.0'
servers:
  - url: 'http://example.web-service.api.com'
    variables: {}
  - url: 'http://example.ingest-service.api.com'
    variables: {}
  - url: 'http://example.translation-service.api.com'
    variables: {}
paths:
  /login:
    post:
      tags:
        - Auth
      summary: Login
      operationId: Login
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
            example:
              username: spladmin
              password: password
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
        - url: 'http://example.web-service.api.com'
          variables: {}
  /organization:
    get:
      tags:
        - Organization
      summary: Organization
      operationId: Organization
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: 'http://example.web-service.api.com'
          variables: {}
  /organization/configuration:
    put:
      tags:
        - Organization
      summary: Organization Configuration
      operationId: OrganizationConfiguration
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationConfigurationRequest'
            example:
              name: Health Authority
              notificationThresholdPercent: 6
              notificationThresholdTimeline: 0
              daysToRetainRecords: 30
              regionCoordinates:
                ne:
                  latitude: 21.312764055951195
                  longitude: -21.45445121262883
                sw:
                  latitude: 21.766025040122642
                  longitude: -21.49442923997258
              apiEndpointUrl: 'https://s3.aws.com/bucket_name'
              referenceWebsiteUrl: 'http://nbc.gov'
              infoWebsiteUrl: 'http://nbc.gov'
              completedOnboarding: true
              privacyPolicyUrl: http//test.com
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: 'http://example.web-service.api.com'
          variables: {}
    get:
      tags:
        - Organization
      summary: Organization Configuration
      operationId: GetOrganizationConfiguration
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: 'http://example.web-service.api.com'
          variables: {}
  /organization/cases:
    get:
      tags:
        - Organization
      summary: Organization Cases
      operationId: OrganizationCases
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: 'http://example.web-service.api.com'
          variables: {}
  /case/delete:
    post:
      tags:
        - Organization
      summary: Delete Case
      operationId: DeleteCase
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteCaseRequest'
            example:
              caseId: 2
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: 'http://example.web-service.api.com'
          variables: {}
  /access-code:
    post:
      tags:
        - Access Codes
      summary: Access Code
      operationId: AccessCode
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: 'http://example.web-service.api.com'
          variables: {}
  /organization/case:
    post:
      tags:
        - Cases
      summary: Create Case
      operationId: CreateCase
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: 'http://example.web-service.api.com'
          variables: {}
  /case:
    put:
      tags:
        - Cases
      summary: Update Case
      operationId: UpdateCase
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCaseRequest'
            example:
              caseId: 1
              externalId: an_id
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: 'http://example.web-service.api.com'
          variables: {}
  /case/consent-to-publishing:
    post:
      tags:
        - Cases
      summary: Consent To Publishing
      operationId: ConsentToPublishing
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsentToPublishingRequest'
            example:
              caseId: 1
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: 'http://example.web-service.api.com'
          variables: {}
  /case/stage:
    post:
      tags:
        - Cases
      summary: Stage Case
      operationId: StageCase
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StageCaseRequest'
            example:
              caseId: 1
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: 'http://example.web-service.api.com'
          variables: {}
  /cases/publish:
    post:
      tags:
        - Cases
      summary: Publish Case
      operationId: PublishCase
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublishCaseRequest'
            example:
              caseIds:
                - 1
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: 'http://example.web-service.api.com'
          variables: {}
  /case/points/ingest:
    post:
      tags:
        - Points Translation Service
      summary: Associate Points to Case
      operationId: AssociatePointstoCase
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssociatePointstoCaseRequest'
            example:
              caseId: 1
              accessCode: '272236'
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: 'http://example.translation-service.api.com'
          variables: {}
  /case/points:
    post:
      tags:
        - Points Translation Service
      summary: Case Points
      operationId: CasePoints
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CasePointsRequest'
            example:
              caseId: 1
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: 'http://example.translation-service.api.com'
          variables: {}
  /case/point:
    post:
      tags:
        - Points Translation Service
      summary: Create Case Point
      operationId: CreateCasePoint
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCasePointRequest'
            example:
              caseId: '1'
              point:
                longitude: '23.183994'
                latitude: '-72.318221'
                time: '2020-06-02T18:25:43.511Z'
                duration: 10
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: 'http://example.translation-service.api.com'
          variables: {}
    put:
      tags:
        - Points Translation Service
      summary: Case Point
      operationId: CasePoint
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CasePointRequest'
            example:
              pointId: 9332
              longitude: '23.183994'
              latitude: '-72.318221'
              time: '2020-06-02T18:25:43.511Z'
              duration: 20
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: 'http://example.translation-service.api.com'
          variables: {}
  /case/point/delete:
    post:
      tags:
        - Points Translation Service
      summary: Delete Case Point
      operationId: DeleteCasePoint
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteCasePointRequest'
            example:
              pointId: 9332
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: 'http://example.translation-service.api.com'
          variables: {}
  /cases/points:
    post:
      tags:
        - Points Translation Service
      summary: Cases Points
      operationId: CasesPoints
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CasesPointsRequest'
            example:
              caseIds:
                - 1
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: 'http://example.translation-service.api.com'
          variables: {}
  /access-code/valid:
    post:
      tags:
        - Ingest Service
      summary: Access Code Valid
      operationId: AccessCodeValid
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccessCodeValidRequest'
            example:
              accessCode: '272236'
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: 'http://example.translation-service.api.com'
          variables: {}
  /consent:
    post:
      tags:
        - Ingest Service
      summary: Consent
      operationId: Consent
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsentRequest'
            example:
              accessCode: '272236'
              consent: true
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: 'http://example.ingest-service.api.com'
          variables: {}
  /upload:
    post:
      tags:
        - Ingest Service
      summary: Upload
      operationId: Upload
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UploadRequest'
            example:
              accessCode: '272236'
              concernPoints:
                - longitude: '23.183994'
                  latitude: '-72.318221'
                  time: 1591307315
                  hash: adfasdfasdf
                - longitude: '23.183994'
                  latitude: '-72.318221'
                  time: 1591307615
                  hash: adfasdfasdf
                - longitude: '23.183994'
                  latitude: '-72.318221'
                  time: 1591307915
                  hash: adfasdfasdf
                - longitude: '23.183994'
                  latitude: '-72.318221'
                  time: 1591308215
                  hash: adfasdfasdf
                - longitude: '24.183994'
                  latitude: '-74.318221'
                  time: 1591221815
                  hash: adfasdfasdf
                - longitude: '24.183994'
                  latitude: '-74.318221'
                  time: 1591222115
                  hash: adfasdfasdf
                - longitude: '25.183994'
                  latitude: '-75.318221'
                  time: 1591134515
                  hash: adfasdfasdf
                - longitude: '21.183994'
                  latitude: '-72.318221'
                  time: 1590961715
                  hash: adfasdfasdf
                - longitude: '22.183994'
                  latitude: '-72.318221'
                  time: 1591122343
                  hash: adfasdfasdf
                - longitude: '23.083994'
                  latitude: '-72.018221'
                  time: 1591115143
                  hash: adfasdfasdf
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: 'http://example.ingest-service.api.com'
          variables: {}
components:
  schemas:
    LoginRequest:
      title: LoginRequest
      required:
        - username
        - password
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      example:
        username: spladmin
        password: password
    OrganizationConfigurationRequest:
      title: OrganizationConfigurationRequest
      required:
        - name
        - notificationThresholdPercent
        - notificationThresholdTimeline
        - daysToRetainRecords
        - regionCoordinates
        - apiEndpointUrl
        - referenceWebsiteUrl
        - infoWebsiteUrl
        - completedOnboarding
        - privacyPolicyUrl
      type: object
      properties:
        name:
          type: string
        notificationThresholdPercent:
          type: integer
          format: int32
        notificationThresholdTimeline:
          type: integer
          format: int32
        daysToRetainRecords:
          type: integer
          format: int32
        regionCoordinates:
          $ref: '#/components/schemas/RegionCoordinates'
        apiEndpointUrl:
          type: string
        referenceWebsiteUrl:
          type: string
        infoWebsiteUrl:
          type: string
        completedOnboarding:
          type: boolean
        privacyPolicyUrl:
          type: string
      example:
        name: Health Authority
        notificationThresholdPercent: 6
        notificationThresholdTimeline: 0
        daysToRetainRecords: 30
        regionCoordinates:
          ne:
            latitude: 21.312764055951195
            longitude: -21.45445121262883
          sw:
            latitude: 21.766025040122642
            longitude: -21.49442923997258
        apiEndpointUrl: 'https://s3.aws.com/bucket_name'
        referenceWebsiteUrl: 'http://nbc.gov'
        infoWebsiteUrl: 'http://nbc.gov'
        completedOnboarding: true
        privacyPolicyUrl: http//test.com
    RegionCoordinates:
      title: RegionCoordinates
      required:
        - ne
        - sw
      type: object
      properties:
        ne:
          $ref: '#/components/schemas/Ne'
        sw:
          $ref: '#/components/schemas/Sw'
      example:
        ne:
          latitude: 21.312764055951195
          longitude: -21.45445121262883
        sw:
          latitude: 21.766025040122642
          longitude: -21.49442923997258
    Ne:
      title: Ne
      required:
        - latitude
        - longitude
      type: object
      properties:
        latitude:
          type: number
        longitude:
          type: number
      example:
        latitude: 21.312764055951195
        longitude: -21.45445121262883
    Sw:
      title: Sw
      required:
        - latitude
        - longitude
      type: object
      properties:
        latitude:
          type: number
        longitude:
          type: number
      example:
        latitude: 21.766025040122642
        longitude: -21.49442923997258
    DeleteCaseRequest:
      title: DeleteCaseRequest
      required:
        - caseId
      type: object
      properties:
        caseId:
          type: integer
          format: int32
      example:
        caseId: 2
    UpdateCaseRequest:
      title: UpdateCaseRequest
      required:
        - caseId
        - externalId
      type: object
      properties:
        caseId:
          type: integer
          format: int32
        externalId:
          type: string
      example:
        caseId: 1
        externalId: an_id
    ConsentToPublishingRequest:
      title: ConsentToPublishingRequest
      required:
        - caseId
      type: object
      properties:
        caseId:
          type: integer
          format: int32
      example:
        caseId: 1
    StageCaseRequest:
      title: StageCaseRequest
      required:
        - caseId
      type: object
      properties:
        caseId:
          type: integer
          format: int32
      example:
        caseId: 1
    PublishCaseRequest:
      title: PublishCaseRequest
      required:
        - caseIds
      type: object
      properties:
        caseIds:
          type: array
          items:
            type: integer
            format: int32
      example:
        caseIds:
          - 1
    AssociatePointstoCaseRequest:
      title: AssociatePointstoCaseRequest
      required:
        - caseId
        - accessCode
      type: object
      properties:
        caseId:
          type: integer
          format: int32
        accessCode:
          type: string
      example:
        caseId: 1
        accessCode: '272236'
    CasePointsRequest:
      title: CasePointsRequest
      required:
        - caseId
      type: object
      properties:
        caseId:
          type: integer
          format: int32
      example:
        caseId: 1
    CreateCasePointRequest:
      title: CreateCasePointRequest
      required:
        - caseId
        - point
      type: object
      properties:
        caseId:
          type: string
        point:
          $ref: '#/components/schemas/Point'
      example:
        caseId: '1'
        point:
          longitude: '23.183994'
          latitude: '-72.318221'
          time: '2020-06-02T18:25:43.511Z'
          duration: 10
    Point:
      title: Point
      required:
        - longitude
        - latitude
        - time
        - duration
      type: object
      properties:
        longitude:
          type: string
        latitude:
          type: string
        time:
          type: string
        duration:
          type: integer
          format: int32
      example:
        longitude: '23.183994'
        latitude: '-72.318221'
        time: '2020-06-02T18:25:43.511Z'
        duration: 10
    CasePointRequest:
      title: CasePointRequest
      required:
        - pointId
        - longitude
        - latitude
        - time
        - duration
      type: object
      properties:
        pointId:
          type: integer
          format: int32
        longitude:
          type: string
        latitude:
          type: string
        time:
          type: string
        duration:
          type: integer
          format: int32
      example:
        pointId: 9332
        longitude: '23.183994'
        latitude: '-72.318221'
        time: '2020-06-02T18:25:43.511Z'
        duration: 20
    DeleteCasePointRequest:
      title: DeleteCasePointRequest
      required:
        - pointId
      type: object
      properties:
        pointId:
          type: integer
          format: int32
      example:
        pointId: 9332
    CasesPointsRequest:
      title: CasesPointsRequest
      required:
        - caseIds
      type: object
      properties:
        caseIds:
          type: array
          items:
            type: integer
            format: int32
      example:
        caseIds:
          - 1
    AccessCodeValidRequest:
      title: AccessCodeValidRequest
      required:
        - accessCode
      type: object
      properties:
        accessCode:
          type: string
      example:
        accessCode: '272236'
    ConsentRequest:
      title: ConsentRequest
      required:
        - accessCode
        - consent
      type: object
      properties:
        accessCode:
          type: string
        consent:
          type: boolean
      example:
        accessCode: '272236'
        consent: true
    UploadRequest:
      title: UploadRequest
      required:
        - accessCode
        - concernPoints
      type: object
      properties:
        accessCode:
          type: string
        concernPoints:
          type: array
          items:
            $ref: '#/components/schemas/ConcernPoint'
      example:
        accessCode: '272236'
        concernPoints:
          - longitude: '23.183994'
            latitude: '-72.318221'
            time: 1591307315
            hash: adfasdfasdf
          - longitude: '23.183994'
            latitude: '-72.318221'
            time: 1591307615
            hash: adfasdfasdf
          - longitude: '23.183994'
            latitude: '-72.318221'
            time: 1591307915
            hash: adfasdfasdf
          - longitude: '23.183994'
            latitude: '-72.318221'
            time: 1591308215
            hash: adfasdfasdf
          - longitude: '24.183994'
            latitude: '-74.318221'
            time: 1591221815
            hash: adfasdfasdf
          - longitude: '24.183994'
            latitude: '-74.318221'
            time: 1591222115
            hash: adfasdfasdf
          - longitude: '25.183994'
            latitude: '-75.318221'
            time: 1591134515
            hash: adfasdfasdf
          - longitude: '21.183994'
            latitude: '-72.318221'
            time: 1590961715
            hash: adfasdfasdf
          - longitude: '22.183994'
            latitude: '-72.318221'
            time: 1591122343
            hash: adfasdfasdf
          - longitude: '23.083994'
            latitude: '-72.018221'
            time: 1591115143
            hash: adfasdfasdf
    ConcernPoint:
      title: ConcernPoint
      required:
        - longitude
        - latitude
        - time
        - hash
      type: object
      properties:
        longitude:
          type: string
        latitude:
          type: string
        time:
          type: integer
          format: int32
        hash:
          type: string
      example:
        longitude: '23.183994'
        latitude: '-72.318221'
        time: 1591307315
        hash: adfasdfasdf
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
security:
  - httpBearer: []
tags:
  - name: Auth
  - name: Organization
  - name: Access Codes
  - name: Cases
  - name: Points Translation Service
  - name: Ingest Service
